{
 "title": "DPtech Exporter Dashboard (Device)",
 "description": "Use Prometheus and the dptech_exporter to collect the statistics of DPtech network devices and display the statistics of DPtech network device.",
 "tags": [
  "dptech_exporter",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(dptech_snmp_info,host)"
    }
   },
   {
    "name": "descr",
    "label": "Descr",
    "query": {
     "query": "label_values(dptech_snmp_info{host=\"$host\"},descr)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(dptech_snmp_info{host=\"$host\"},location)"
    }
   },
   {
    "name": "contact",
    "label": "Contact",
    "query": {
     "query": "label_values(dptech_snmp_info{host=\"$host\"},contact)"
    }
   },
   {
    "name": "sysname",
    "label": "Sysname",
    "query": {
     "query": "label_values(dptech_snmp_info{host=\"$host\"},sysname)"
    }
   },
   {
    "name": "model",
    "label": "Model",
    "query": {
     "query": "label_values(dptech_snmp_info{host=\"$host\"},model)"
    }
   },
   {
    "name": "cards",
    "label": "Cards",
    "query": {
     "query": "query_result(count(dptech_card_cpu_usage_percent{host=\"$host\",card=~\"$card\"}))"
    }
   },
   {
    "name": "card",
    "label": "Card",
    "query": {
     "query": "label_values(dptech_card_cpu_usage_percent{host=\"$host\"},card)"
    }
   },
   {
    "name": "iftotal",
    "query": {
     "query": "query_result(count(dptech_if_status{host=\"$host\"}))"
    }
   },
   {
    "name": "ifused",
    "query": {
     "query": "query_result(count(dptech_if_status{host=\"$host\"}>0))"
    }
   },
   {
    "name": "iftype",
    "label": "Iftype",
    "query": {
     "query": "label_values(dptech_if_status{host=\"$host\"},iftype)"
    }
   },
   {
    "name": "ifname",
    "label": "Ifname",
    "query": {
     "query": "label_values(dptech_if_status{host=\"$host\"},ifname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System (Host: $host Sysname: $sysname Model: $model)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_cpu_usage_percent{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_memory_usage_percent{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_cpu_temperature_degree{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Mainboard Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_mainboard_temperature_degree{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_snmp_status{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<pre style=\"margin:0;padding:0;border:none;color:#73bf69;\">${descr}</pre>\r\n\r\n"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_uptime_seconds{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_snmp_info{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dptech_cpu_usage_percent{host=~\"$host\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "dptech_memory_usage_percent{host=~\"$host\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dptech_cpu_temperature_degree{host=~\"$host\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "dptech_mainboard_temperature_degree{host=~\"$host\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Sysname",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_snmp_info{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_snmp_info{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Location",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": {
    "content": "<pre style=\"margin:0;padding:0;border:none;color:#73bf69;\">${location}</pre>\r\n\r\n"
   }
  },
  {
   "title": "SN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_snmp_info{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_snmp_info{host=~\"$host\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Contact",
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "options": {
    "content": "<pre style=\"margin:0;padding:0;border:none;color:#73bf69;\">${contact}</pre>\r\n\r\n"
   }
  },
  { "title": "Cards (Total: $cards)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cards",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "dptech_card_cpu_usage_percent{host=~\"$host\", card=~\"$card\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "dptech_card_memory_usage_percent{host=~\"$host\", card=~\"$card\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "dptech_card_lcpu_usage_percent{host=~\"$host\", card=~\"$card\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "dptech_card_lmem_usage_percent{host=~\"$host\", card=~\"$card\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "dptech_card_cpu_temperature_degree{host=~\"$host\", card=~\"$card\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "dptech_card_temperature_degree{host=~\"$host\", card=~\"$card\"} - 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU And LCPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dptech_card_cpu_usage_percent{host=\"$host\", card=~\"$card\"}>0",
     "legendFormat": "Slot {{slot}}: {{card}} CPU"
    },
    {
     "expr": "dptech_card_lcpu_usage_percent{host=\"$host\", card=~\"$card\"}>0",
     "legendFormat": "Slot {{slot}}: {{card}} LCPU"
    }
   ]
  },
  {
   "title": "Memory And LMEM Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dptech_card_memory_usage_percent{host=\"$host\", card=~\"$card\"}>0",
     "legendFormat": "Slot {{slot}}: {{card}} Memory"
    },
    {
     "expr": "dptech_card_lmem_usage_percent{host=\"$host\", card=~\"$card\"}>0",
     "legendFormat": "Slot {{slot}}: {{card}} LMEM"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dptech_card_cpu_temperature_degree{host=\"$host\", card=~\"$card\"}>0",
     "legendFormat": "Slot {{slot}}: {{card}} CPU"
    }
   ]
  },
  {
   "title": "Card Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dptech_card_temperature_degree{host=\"$host\", card=~\"$card\"}>0",
     "legendFormat": "Slot {{slot}}: {{card}} CPU"
    }
   ]
  },
  {
   "title": "Interfaces (Total: $iftotal Up: $ifused)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dptech_if_status{host=\"$host\", iftype=~\"$iftype\"}) by (iftype)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top5 Inbound Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_in_usage_percent{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_out_usage_percent{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"status\", dptech_if_status{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed(Mbps)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10000, count_values('speed', dptech_if_speed_bps{host=\"$host\", iftype=~\"$iftype\"}/1000000>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Speed (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(dptech_if_in_bps{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(dptech_if_out_bps{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Discards and Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(dptech_if_in_discards_pps{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "Inbound Discards"
    },
    {
     "expr": "sum(dptech_if_out_discards_pps{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "Outbound Discards"
    },
    {
     "expr": "sum(dptech_if_in_errors_pps{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "Inbound Errors"
    },
    {
     "expr": "sum(dptech_if_out_errors_pps{host=\"$host\", iftype=~\"$iftype\"})",
     "legendFormat": "Outbound Errors"
    }
   ]
  },
  {
   "title": "Top5 Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "dptech_if_in_bps{host=\"$host\", iftype=~\"$iftype\"} and on(ifname) (topk(5, delta(dptech_if_in_bytes{host=\"$host\", iftype=~\"$iftype\"}[$__range])>0))",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "dptech_if_out_bps{host=\"$host\", iftype=~\"$iftype\"} and on(ifname) (topk(5, delta(dptech_if_out_bytes{host=\"$host\", iftype=~\"$iftype\"}[$__range])>0))",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Inbound Discards",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "dptech_if_in_discards_pps{host=\"$host\", iftype=~\"$iftype\"} and on(ifname) (topk(5, delta(dptech_if_in_discards{host=\"$host\", iftype=~\"$iftype\"}[$__range])>0))",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Discards",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "dptech_if_out_discards_pps{host=\"$host\", iftype=~\"$iftype\"} and on(ifname) (topk(5, delta(dptech_if_out_discards{host=\"$host\", iftype=~\"$iftype\"}[$__range])>0))",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Inbound Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "dptech_if_in_errors_pps{host=\"$host\", iftype=~\"$iftype\"} and on(ifname) (topk(5, delta(dptech_if_in_errors{host=\"$host\", iftype=~\"$iftype\"}[$__range])>0))",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "dptech_if_out_errors_pps{host=\"$host\", iftype=~\"$iftype\"} and on(ifname) (topk(5, delta(dptech_if_out_errors{host=\"$host\", iftype=~\"$iftype\"}[$__range])>0))",
     "legendFormat": "{{ifname}}"
    }
   ]
  },
  { "title": "Interface ($ifname)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_if_status{host=\"$host\", ifname=\"$ifname\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Ifdescr",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_if_status{host=\"$host\", ifname=\"$ifname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iftype",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_if_status{host=\"$host\", ifname=\"$ifname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_if_speed_bps{host=\"$host\", ifname=\"$ifname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Speed(Inbound)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_if_in_bps{host=\"$host\", ifname=\"$ifname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Speed(Outbound)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dptech_if_out_bps{host=\"$host\", ifname=\"$ifname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dptech_if_in_usage_percent{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Inbound"
    },
    {
     "expr": "dptech_if_out_usage_percent{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 99 },
   "targets": [
    {
     "expr": "dptech_if_in_bps{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Current Speed"
    },
    {
     "expr": "dptech_if_in_discards_pps{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Discards"
    },
    {
     "expr": "dptech_if_in_errors_pps{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 99 },
   "targets": [
    {
     "expr": "dptech_if_out_bps{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Current Speed"
    },
    {
     "expr": "dptech_if_out_discards_pps{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Discards"
    },
    {
     "expr": "dptech_if_out_errors_pps{host=\"$host\", ifname=\"$ifname\"}>0",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}