{
 "title": "DPtech Exporter Dashboard (Overview)",
 "description": "Use Prometheus and the dptech_exporter to collect the statistics of DPtech network devices and display the statistics of DPtech network devices.",
 "tags": [
  "Prometheus",
  "dptech_exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(dptech_snmp_status,host)"
    }
   },
   {
    "name": "sysname",
    "label": "Sysname",
    "query": {
     "query": "label_values(dptech_snmp_status,sysname)"
    }
   },
   {
    "name": "total",
    "label": "total_hosts",
    "query": {
     "query": "query_result(count(dptech_snmp_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"}))"
    }
   },
   {
    "name": "model",
    "label": "Model",
    "query": {
     "query": "label_values(dptech_snmp_status,model)"
    }
   },
   {
    "name": "card",
    "label": "Card",
    "query": {
     "query": "label_values(dptech_card_cpu_usage_percent,card)"
    }
   },
   {
    "name": "iftype",
    "label": "Iftype",
    "query": {
     "query": "label_values(dptech_if_status,iftype)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview (Total: $total)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "dptech_snmp_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"} - 0",
     "legendFormat": "host"
    },
    { "expr": "dptech_cpu_usage_percent - 0", "legendFormat": "cpu" },
    {
     "expr": "dptech_memory_usage_percent - 0",
     "legendFormat": "memory"
    },
    {
     "expr": "dptech_cpu_temperature_degree - 0",
     "legendFormat": "cpu_temp"
    },
    {
     "expr": "dptech_mainboard_temperature_degree - 0",
     "legendFormat": "mb_temp"
    },
    { "expr": "dptech_uptime_seconds", "legendFormat": "uptime" },
    {
     "expr": "count(dptech_card_cpu_usage_percent) by (host, sysname)",
     "legendFormat": "cards"
    },
    {
     "expr": "count(dptech_if_status>0) by (host, sysname)",
     "legendFormat": "ifs_up"
    },
    { "expr": "dptech_snmp_info - 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values('status', dptech_snmp_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Models",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dptech_snmp_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"}) by (model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top5 CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_cpu_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"}) - 0",
     "legendFormat": "{{host}} ({{sysname}})"
    }
   ]
  },
  {
   "title": "Top5 Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_memory_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"}) - 0",
     "legendFormat": "{{host}} ({{sysname}})"
    }
   ]
  },
  {
   "title": "Top5 CPU Temperature",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_cpu_temperature_degree{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"}) - 0",
     "legendFormat": "{{host}} ({{sysname}})"
    }
   ]
  },
  {
   "title": "Top5 Mainboard Temperature",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_mainboard_temperature_degree{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"}) - 0",
     "legendFormat": "{{host}} ({{sysname}})"
    }
   ]
  },
  {
   "title": "Down Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "dptech_snmp_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"}==0 - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "dptech_snmp_last_time * 1000 - 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_values('status', dptech_snmp_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(dptech_card_cpu_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"})",
     "legendFormat": "Cards"
    },
    {
     "expr": "count(dptech_if_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\"})",
     "legendFormat": "Interfaces"
    }
   ]
  },
  { "title": "Cards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Models",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dptech_card_cpu_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", card=~\"$card\"}) by (card)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top5 CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_card_cpu_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", card=~\"$card\"})",
     "legendFormat": "{{host}} slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top5 Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_card_memory_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", card=~\"$card\"})",
     "legendFormat": "{{host}} slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top5 CPU Temperature",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk(5, dptech_card_cpu_temperature_degree{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", card=~\"$card\"})",
     "legendFormat": "{{host}} slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top5 Card Temperature",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk(5, dptech_card_temperature_degree{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", card=~\"$card\"})",
     "legendFormat": "{{host}} slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top5 LCPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_card_lcpu_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", card=~\"$card\"}>0)",
     "legendFormat": "{{host}} slot {{slot}}"
    }
   ]
  },
  {
   "title": "Top5 LMEM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_card_lmem_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", card=~\"$card\"}>0)",
     "legendFormat": "{{host}} slot {{slot}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dptech_if_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"}) by (iftype)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top5 Inbound Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_in_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_out_usage_percent{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values('status', dptech_if_status{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed(Mbps)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10000, count_values('speed', dptech_if_speed_bps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"}/1000000>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Speed (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(dptech_if_in_bps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(dptech_if_out_bps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Top5 Inbound Current Speed",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_in_bps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Current Speed",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_out_bps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Discards and Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(dptech_if_in_discards_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "Inbound Discards"
    },
    {
     "expr": "sum(dptech_if_out_discards_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "Outbound Discards"
    },
    {
     "expr": "sum(dptech_if_in_errors_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "Inbound Errors"
    },
    {
     "expr": "sum(dptech_if_out_errors_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"})",
     "legendFormat": "Outbound Errors"
    }
   ]
  },
  {
   "title": "Top5 Inbound Discards",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_in_discards_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"}>0)",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Discards",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_out_discards_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"}>0)",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Inbound Errors",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_in_errors_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"}>0)",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  },
  {
   "title": "Top5 Outbound Errors",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, dptech_if_out_errors_pps{host=~\"$host\", sysname=~\"$sysname\", model=~\"$model\", iftype=~\"$iftype\"}>0)",
     "legendFormat": "{{host}} {{ifname}}"
    }
   ]
  }
 ]
}